// Extended country mappings with 150 countries
export const countryMappings = {
  // Americas
  'BRA': { lang: 'pt', currency: 'BRL', currencySymbol: 'R$', country: 'Brazil', flag: '🇧🇷', paymentMethod: 'PIX/Boleto' },
  'USA': { lang: 'en', currency: 'USD', currencySymbol: '$', country: 'United States', flag: '🇺🇸', paymentMethod: 'SWIFT Wire' },
  'CAN': { lang: 'en', currency: 'CAD', currencySymbol: 'C$', country: 'Canada', flag: '🇨🇦', paymentMethod: 'SWIFT Wire' },
  'MEX': { lang: 'es', currency: 'MXN', currencySymbol: '$', country: 'Mexico', flag: '🇲🇽', paymentMethod: 'SWIFT Wire' },
  'ARG': { lang: 'es', currency: 'ARS', currencySymbol: '$', country: 'Argentina', flag: '🇦🇷', paymentMethod: 'SWIFT Wire' },
  'COL': { lang: 'es', currency: 'COP', currencySymbol: '$', country: 'Colombia', flag: '🇨🇴', paymentMethod: 'SWIFT Wire' },
  'PER': { lang: 'es', currency: 'PEN', currencySymbol: 'S/', country: 'Peru', flag: '🇵🇪', paymentMethod: 'SWIFT Wire' },
  'CHL': { lang: 'es', currency: 'CLP', currencySymbol: '$', country: 'Chile', flag: '🇨🇱', paymentMethod: 'SWIFT Wire' },
  'VEN': { lang: 'es', currency: 'VED', currencySymbol: 'Bs', country: 'Venezuela', flag: '🇻🇪', paymentMethod: 'SWIFT Wire' },
  'ECU': { lang: 'es', currency: 'USD', currencySymbol: '$', country: 'Ecuador', flag: '🇪🇨', paymentMethod: 'SWIFT Wire' },
  'BOL': { lang: 'es', currency: 'BOB', currencySymbol: 'Bs', country: 'Bolivia', flag: '🇧🇴', paymentMethod: 'SWIFT Wire' },
  'PRY': { lang: 'es', currency: 'PYG', currencySymbol: '₲', country: 'Paraguay', flag: '🇵🇾', paymentMethod: 'SWIFT Wire' },
  'URY': { lang: 'es', currency: 'UYU', currencySymbol: '$', country: 'Uruguay', flag: '🇺🇾', paymentMethod: 'SWIFT Wire' },
  'GUY': { lang: 'en', currency: 'GYD', currencySymbol: '$', country: 'Guyana', flag: '🇬🇾', paymentMethod: 'SWIFT Wire' },
  'SUR': { lang: 'en', currency: 'SRD', currencySymbol: '$', country: 'Suriname', flag: '🇸🇷', paymentMethod: 'SWIFT Wire' },
  'CUB': { lang: 'es', currency: 'CUP', currencySymbol: '$', country: 'Cuba', flag: '🇨🇺', paymentMethod: 'SWIFT Wire' },
  'DOM': { lang: 'es', currency: 'DOP', currencySymbol: 'RD$', country: 'Dominican Republic', flag: '🇩🇴', paymentMethod: 'SWIFT Wire' },
  'HTI': { lang: 'fr', currency: 'HTG', currencySymbol: 'G', country: 'Haiti', flag: '🇭🇹', paymentMethod: 'SWIFT Wire' },
  'JAM': { lang: 'en', currency: 'JMD', currencySymbol: 'J$', country: 'Jamaica', flag: '🇯🇲', paymentMethod: 'SWIFT Wire' },
  'CRI': { lang: 'es', currency: 'CRC', currencySymbol: '₡', country: 'Costa Rica', flag: '🇨🇷', paymentMethod: 'SWIFT Wire' },
  'PAN': { lang: 'es', currency: 'PAB', currencySymbol: 'B/.', country: 'Panama', flag: '🇵🇦', paymentMethod: 'SWIFT Wire' },
  'GTM': { lang: 'es', currency: 'GTQ', currencySymbol: 'Q', country: 'Guatemala', flag: '🇬🇹', paymentMethod: 'SWIFT Wire' },
  'HND': { lang: 'es', currency: 'HNL', currencySymbol: 'L', country: 'Honduras', flag: '🇭🇳', paymentMethod: 'SWIFT Wire' },
  'NIC': { lang: 'es', currency: 'NIO', currencySymbol: 'C$', country: 'Nicaragua', flag: '🇳🇮', paymentMethod: 'SWIFT Wire' },
  'SLV': { lang: 'es', currency: 'USD', currencySymbol: '$', country: 'El Salvador', flag: '🇸🇻', paymentMethod: 'SWIFT Wire' },
  'BLZ': { lang: 'en', currency: 'BZD', currencySymbol: 'BZ$', country: 'Belize', flag: '🇧🇿', paymentMethod: 'SWIFT Wire' },

  // Europe  
  'ESP': { lang: 'es', currency: 'EUR', currencySymbol: '€', country: 'Spain', flag: '🇪🇸', paymentMethod: 'SWIFT Wire' },
  'DEU': { lang: 'de', currency: 'EUR', currencySymbol: '€', country: 'Germany', flag: '🇩🇪', paymentMethod: 'SWIFT Wire' },
  'FRA': { lang: 'fr', currency: 'EUR', currencySymbol: '€', country: 'France', flag: '🇫🇷', paymentMethod: 'SWIFT Wire' },
  'ITA': { lang: 'it', currency: 'EUR', currencySymbol: '€', country: 'Italy', flag: '🇮🇹', paymentMethod: 'SWIFT Wire' },
  'GBR': { lang: 'en', currency: 'GBP', currencySymbol: '£', country: 'United Kingdom', flag: '🇬🇧', paymentMethod: 'SWIFT Wire' },
  'NLD': { lang: 'en', currency: 'EUR', currencySymbol: '€', country: 'Netherlands', flag: '🇳🇱', paymentMethod: 'SWIFT Wire' },
  'CHE': { lang: 'de', currency: 'CHF', currencySymbol: 'Fr', country: 'Switzerland', flag: '🇨🇭', paymentMethod: 'SWIFT Wire' },
  'SWE': { lang: 'en', currency: 'SEK', currencySymbol: 'kr', country: 'Sweden', flag: '🇸🇪', paymentMethod: 'SWIFT Wire' },
  'NOR': { lang: 'en', currency: 'NOK', currencySymbol: 'kr', country: 'Norway', flag: '🇳🇴', paymentMethod: 'SWIFT Wire' },
  'DNK': { lang: 'en', currency: 'DKK', currencySymbol: 'kr', country: 'Denmark', flag: '🇩🇰', paymentMethod: 'SWIFT Wire' },
  'FIN': { lang: 'en', currency: 'EUR', currencySymbol: '€', country: 'Finland', flag: '🇫🇮', paymentMethod: 'SWIFT Wire' },
  'BEL': { lang: 'fr', currency: 'EUR', currencySymbol: '€', country: 'Belgium', flag: '🇧🇪', paymentMethod: 'SWIFT Wire' },
  'AUT': { lang: 'de', currency: 'EUR', currencySymbol: '€', country: 'Austria', flag: '🇦🇹', paymentMethod: 'SWIFT Wire' },
  'PRT': { lang: 'pt', currency: 'EUR', currencySymbol: '€', country: 'Portugal', flag: '🇵🇹', paymentMethod: 'SWIFT Wire' },
  'POL': { lang: 'en', currency: 'PLN', currencySymbol: 'zł', country: 'Poland', flag: '🇵🇱', paymentMethod: 'SWIFT Wire' },
  'ROU': { lang: 'en', currency: 'RON', currencySymbol: 'lei', country: 'Romania', flag: '🇷🇴', paymentMethod: 'SWIFT Wire' },
  'GRC': { lang: 'en', currency: 'EUR', currencySymbol: '€', country: 'Greece', flag: '🇬🇷', paymentMethod: 'SWIFT Wire' },
  'CZE': { lang: 'en', currency: 'CZK', currencySymbol: 'Kč', country: 'Czech Republic', flag: '🇨🇿', paymentMethod: 'SWIFT Wire' },
  'SVK': { lang: 'en', currency: 'EUR', currencySymbol: '€', country: 'Slovakia', flag: '🇸🇰', paymentMethod: 'SWIFT Wire' },
  'HUN': { lang: 'en', currency: 'HUF', currencySymbol: 'Ft', country: 'Hungary', flag: '🇭🇺', paymentMethod: 'SWIFT Wire' },
  'BGR': { lang: 'en', currency: 'BGN', currencySymbol: 'лв', country: 'Bulgaria', flag: '🇧🇬', paymentMethod: 'SWIFT Wire' },
  'HRV': { lang: 'en', currency: 'EUR', currencySymbol: '€', country: 'Croatia', flag: '🇭🇷', paymentMethod: 'SWIFT Wire' },
  'SVN': { lang: 'en', currency: 'EUR', currencySymbol: '€', country: 'Slovenia', flag: '🇸🇮', paymentMethod: 'SWIFT Wire' },
  'LTU': { lang: 'en', currency: 'EUR', currencySymbol: '€', country: 'Lithuania', flag: '🇱🇹', paymentMethod: 'SWIFT Wire' },
  'LVA': { lang: 'en', currency: 'EUR', currencySymbol: '€', country: 'Latvia', flag: '🇱🇻', paymentMethod: 'SWIFT Wire' },
  'EST': { lang: 'en', currency: 'EUR', currencySymbol: '€', country: 'Estonia', flag: '🇪🇪', paymentMethod: 'SWIFT Wire' },
  'IRL': { lang: 'en', currency: 'EUR', currencySymbol: '€', country: 'Ireland', flag: '🇮🇪', paymentMethod: 'SWIFT Wire' },
  'ISL': { lang: 'en', currency: 'ISK', currencySymbol: 'kr', country: 'Iceland', flag: '🇮🇸', paymentMethod: 'SWIFT Wire' },
  'LUX': { lang: 'fr', currency: 'EUR', currencySymbol: '€', country: 'Luxembourg', flag: '🇱🇺', paymentMethod: 'SWIFT Wire' },
  'MLT': { lang: 'en', currency: 'EUR', currencySymbol: '€', country: 'Malta', flag: '🇲🇹', paymentMethod: 'SWIFT Wire' },
  'CYP': { lang: 'en', currency: 'EUR', currencySymbol: '€', country: 'Cyprus', flag: '🇨🇾', paymentMethod: 'SWIFT Wire' },

  // Asia
  'CHN': { lang: 'en', currency: 'CNY', currencySymbol: '¥', country: 'China', flag: '🇨🇳', paymentMethod: 'SWIFT Wire' },
  'JPN': { lang: 'en', currency: 'JPY', currencySymbol: '¥', country: 'Japan', flag: '🇯🇵', paymentMethod: 'SWIFT Wire' },
  'KOR': { lang: 'en', currency: 'KRW', currencySymbol: '₩', country: 'South Korea', flag: '🇰🇷', paymentMethod: 'SWIFT Wire' },
  'IND': { lang: 'en', currency: 'INR', currencySymbol: '₹', country: 'India', flag: '🇮🇳', paymentMethod: 'SWIFT Wire' },
  'SGP': { lang: 'en', currency: 'SGD', currencySymbol: 'S$', country: 'Singapore', flag: '🇸🇬', paymentMethod: 'SWIFT Wire' },
  'HKG': { lang: 'en', currency: 'HKD', currencySymbol: 'HK$', country: 'Hong Kong', flag: '🇭🇰', paymentMethod: 'SWIFT Wire' },
  'TWN': { lang: 'en', currency: 'TWD', currencySymbol: 'NT$', country: 'Taiwan', flag: '🇹🇼', paymentMethod: 'SWIFT Wire' },
  'THA': { lang: 'en', currency: 'THB', currencySymbol: '฿', country: 'Thailand', flag: '🇹🇭', paymentMethod: 'SWIFT Wire' },
  'VNM': { lang: 'en', currency: 'VND', currencySymbol: '₫', country: 'Vietnam', flag: '🇻🇳', paymentMethod: 'SWIFT Wire' },
  'IDN': { lang: 'en', currency: 'IDR', currencySymbol: 'Rp', country: 'Indonesia', flag: '🇮🇩', paymentMethod: 'SWIFT Wire' },
  'MYS': { lang: 'en', currency: 'MYR', currencySymbol: 'RM', country: 'Malaysia', flag: '🇲🇾', paymentMethod: 'SWIFT Wire' },
  'PHL': { lang: 'en', currency: 'PHP', currencySymbol: '₱', country: 'Philippines', flag: '🇵🇭', paymentMethod: 'SWIFT Wire' },
  'PAK': { lang: 'en', currency: 'PKR', currencySymbol: '₨', country: 'Pakistan', flag: '🇵🇰', paymentMethod: 'SWIFT Wire' },
  'BGD': { lang: 'en', currency: 'BDT', currencySymbol: '৳', country: 'Bangladesh', flag: '🇧🇩', paymentMethod: 'SWIFT Wire' },
  'LKA': { lang: 'en', currency: 'LKR', currencySymbol: '₨', country: 'Sri Lanka', flag: '🇱🇰', paymentMethod: 'SWIFT Wire' },
  'NPL': { lang: 'en', currency: 'NPR', currencySymbol: '₨', country: 'Nepal', flag: '🇳🇵', paymentMethod: 'SWIFT Wire' },
  'IRN': { lang: 'en', currency: 'IRR', currencySymbol: '﷼', country: 'Iran', flag: '🇮🇷', paymentMethod: 'SWIFT Wire' },
  'TUR': { lang: 'en', currency: 'TRY', currencySymbol: '₺', country: 'Turkey', flag: '🇹🇷', paymentMethod: 'SWIFT Wire' },
  'SAU': { lang: 'en', currency: 'SAR', currencySymbol: '﷼', country: 'Saudi Arabia', flag: '🇸🇦', paymentMethod: 'SWIFT Wire' },
  'ARE': { lang: 'en', currency: 'AED', currencySymbol: 'د.إ', country: 'United Arab Emirates', flag: '🇦🇪', paymentMethod: 'SWIFT Wire' },
  'ISR': { lang: 'en', currency: 'ILS', currencySymbol: '₪', country: 'Israel', flag: '🇮🇱', paymentMethod: 'SWIFT Wire' },
  'JOR': { lang: 'en', currency: 'JOD', currencySymbol: 'د.ا', country: 'Jordan', flag: '🇯🇴', paymentMethod: 'SWIFT Wire' },
  'LBN': { lang: 'en', currency: 'LBP', currencySymbol: 'ل.ل', country: 'Lebanon', flag: '🇱🇧', paymentMethod: 'SWIFT Wire' },
  'KWT': { lang: 'en', currency: 'KWD', currencySymbol: 'د.ك', country: 'Kuwait', flag: '🇰🇼', paymentMethod: 'SWIFT Wire' },
  'QAT': { lang: 'en', currency: 'QAR', currencySymbol: '﷼', country: 'Qatar', flag: '🇶🇦', paymentMethod: 'SWIFT Wire' },
  'BHR': { lang: 'en', currency: 'BHD', currencySymbol: '.د.ب', country: 'Bahrain', flag: '🇧🇭', paymentMethod: 'SWIFT Wire' },
  'OMN': { lang: 'en', currency: 'OMR', currencySymbol: '﷼', country: 'Oman', flag: '🇴🇲', paymentMethod: 'SWIFT Wire' },
  'UZB': { lang: 'en', currency: 'UZS', currencySymbol: 'лв', country: 'Uzbekistan', flag: '🇺🇿', paymentMethod: 'SWIFT Wire' },
  'KAZ': { lang: 'en', currency: 'KZT', currencySymbol: '₸', country: 'Kazakhstan', flag: '🇰🇿', paymentMethod: 'SWIFT Wire' },
  'KGZ': { lang: 'en', currency: 'KGS', currencySymbol: 'лв', country: 'Kyrgyzstan', flag: '🇰🇬', paymentMethod: 'SWIFT Wire' },
  'TJK': { lang: 'en', currency: 'TJS', currencySymbol: 'SM', country: 'Tajikistan', flag: '🇹🇯', paymentMethod: 'SWIFT Wire' },
  'TKM': { lang: 'en', currency: 'TMT', currencySymbol: 'T', country: 'Turkmenistan', flag: '🇹🇲', paymentMethod: 'SWIFT Wire' },
  'AFG': { lang: 'en', currency: 'AFN', currencySymbol: '؋', country: 'Afghanistan', flag: '🇦🇫', paymentMethod: 'SWIFT Wire' },

  // Africa
  'ZAF': { lang: 'en', currency: 'ZAR', currencySymbol: 'R', country: 'South Africa', flag: '🇿🇦', paymentMethod: 'SWIFT Wire' },
  'EGY': { lang: 'en', currency: 'EGP', currencySymbol: '£', country: 'Egypt', flag: '🇪🇬', paymentMethod: 'SWIFT Wire' },
  'NGA': { lang: 'en', currency: 'NGN', currencySymbol: '₦', country: 'Nigeria', flag: '🇳🇬', paymentMethod: 'SWIFT Wire' },
  'KEN': { lang: 'en', currency: 'KES', currencySymbol: 'KSh', country: 'Kenya', flag: '🇰🇪', paymentMethod: 'SWIFT Wire' },
  'ETH': { lang: 'en', currency: 'ETB', currencySymbol: 'Br', country: 'Ethiopia', flag: '🇪🇹', paymentMethod: 'SWIFT Wire' },
  'UGA': { lang: 'en', currency: 'UGX', currencySymbol: 'USh', country: 'Uganda', flag: '🇺🇬', paymentMethod: 'SWIFT Wire' },
  'TZA': { lang: 'en', currency: 'TZS', currencySymbol: 'TSh', country: 'Tanzania', flag: '🇹🇿', paymentMethod: 'SWIFT Wire' },
  'GHA': { lang: 'en', currency: 'GHS', currencySymbol: '₵', country: 'Ghana', flag: '🇬🇭', paymentMethod: 'SWIFT Wire' },
  'CIV': { lang: 'fr', currency: 'XOF', currencySymbol: 'CFA', country: 'Ivory Coast', flag: '🇨🇮', paymentMethod: 'SWIFT Wire' },
  'SEN': { lang: 'fr', currency: 'XOF', currencySymbol: 'CFA', country: 'Senegal', flag: '🇸🇳', paymentMethod: 'SWIFT Wire' },
  'BFA': { lang: 'fr', currency: 'XOF', currencySymbol: 'CFA', country: 'Burkina Faso', flag: '🇧🇫', paymentMethod: 'SWIFT Wire' },
  'MLI': { lang: 'fr', currency: 'XOF', currencySymbol: 'CFA', country: 'Mali', flag: '🇲🇱', paymentMethod: 'SWIFT Wire' },
  'NER': { lang: 'fr', currency: 'XOF', currencySymbol: 'CFA', country: 'Niger', flag: '🇳🇪', paymentMethod: 'SWIFT Wire' },
  'TCD': { lang: 'fr', currency: 'XAF', currencySymbol: 'FCFA', country: 'Chad', flag: '🇹🇩', paymentMethod: 'SWIFT Wire' },
  'CMR': { lang: 'fr', currency: 'XAF', currencySymbol: 'FCFA', country: 'Cameroon', flag: '🇨🇲', paymentMethod: 'SWIFT Wire' },
  'GAB': { lang: 'fr', currency: 'XAF', currencySymbol: 'FCFA', country: 'Gabon', flag: '🇬🇦', paymentMethod: 'SWIFT Wire' },
  'COG': { lang: 'fr', currency: 'XAF', currencySymbol: 'FCFA', country: 'Republic of the Congo', flag: '🇨🇬', paymentMethod: 'SWIFT Wire' },
  'CAF': { lang: 'fr', currency: 'XAF', currencySymbol: 'FCFA', country: 'Central African Republic', flag: '🇨🇫', paymentMethod: 'SWIFT Wire' },
  'GNQ': { lang: 'es', currency: 'XAF', currencySymbol: 'FCFA', country: 'Equatorial Guinea', flag: '🇬🇶', paymentMethod: 'SWIFT Wire' },
  'MDG': { lang: 'fr', currency: 'MGA', currencySymbol: 'Ar', country: 'Madagascar', flag: '🇲🇬', paymentMethod: 'SWIFT Wire' },
  'MWI': { lang: 'en', currency: 'MWK', currencySymbol: 'MK', country: 'Malawi', flag: '🇲🇼', paymentMethod: 'SWIFT Wire' },
  'ZMB': { lang: 'en', currency: 'ZMW', currencySymbol: 'K', country: 'Zambia', flag: '🇿🇲', paymentMethod: 'SWIFT Wire' },
  'ZWE': { lang: 'en', currency: 'ZWL', currencySymbol: '$', country: 'Zimbabwe', flag: '🇿🇼', paymentMethod: 'SWIFT Wire' },
  'BWA': { lang: 'en', currency: 'BWP', currencySymbol: 'P', country: 'Botswana', flag: '🇧🇼', paymentMethod: 'SWIFT Wire' },
  'NAM': { lang: 'en', currency: 'NAD', currencySymbol: '$', country: 'Namibia', flag: '🇳🇦', paymentMethod: 'SWIFT Wire' },
  'LSO': { lang: 'en', currency: 'LSL', currencySymbol: 'M', country: 'Lesotho', flag: '🇱🇸', paymentMethod: 'SWIFT Wire' },
  'SWZ': { lang: 'en', currency: 'SZL', currencySymbol: 'E', country: 'Eswatini', flag: '🇸🇿', paymentMethod: 'SWIFT Wire' },
  'MOZ': { lang: 'pt', currency: 'MZN', currencySymbol: 'MT', country: 'Mozambique', flag: '🇲🇿', paymentMethod: 'SWIFT Wire' },
  'AGO': { lang: 'pt', currency: 'AOA', currencySymbol: 'Kz', country: 'Angola', flag: '🇦🇴', paymentMethod: 'SWIFT Wire' },
  'MAR': { lang: 'fr', currency: 'MAD', currencySymbol: 'د.م.', country: 'Morocco', flag: '🇲🇦', paymentMethod: 'SWIFT Wire' },
  'DZA': { lang: 'fr', currency: 'DZD', currencySymbol: 'د.ج', country: 'Algeria', flag: '🇩🇿', paymentMethod: 'SWIFT Wire' },
  'TUN': { lang: 'fr', currency: 'TND', currencySymbol: 'د.ت', country: 'Tunisia', flag: '🇹🇳', paymentMethod: 'SWIFT Wire' },
  'LBY': { lang: 'en', currency: 'LYD', currencySymbol: 'ل.د', country: 'Libya', flag: '🇱🇾', paymentMethod: 'SWIFT Wire' },

  // Oceania
  'AUS': { lang: 'en', currency: 'AUD', currencySymbol: 'A$', country: 'Australia', flag: '🇦🇺', paymentMethod: 'SWIFT Wire' },
  'NZL': { lang: 'en', currency: 'NZD', currencySymbol: 'NZ$', country: 'New Zealand', flag: '🇳🇿', paymentMethod: 'SWIFT Wire' },
  'FJI': { lang: 'en', currency: 'FJD', currencySymbol: '$', country: 'Fiji', flag: '🇫🇯', paymentMethod: 'SWIFT Wire' },
  'PNG': { lang: 'en', currency: 'PGK', currencySymbol: 'K', country: 'Papua New Guinea', flag: '🇵🇬', paymentMethod: 'SWIFT Wire' },

  // Additional European Countries
  'RUS': { lang: 'en', currency: 'RUB', currencySymbol: '₽', country: 'Russia', flag: '🇷🇺', paymentMethod: 'SWIFT Wire' },
  'UKR': { lang: 'en', currency: 'UAH', currencySymbol: '₴', country: 'Ukraine', flag: '🇺🇦', paymentMethod: 'SWIFT Wire' },
  'BLR': { lang: 'en', currency: 'BYN', currencySymbol: 'Br', country: 'Belarus', flag: '🇧🇾', paymentMethod: 'SWIFT Wire' },
  'MDA': { lang: 'en', currency: 'MDL', currencySymbol: 'L', country: 'Moldova', flag: '🇲🇩', paymentMethod: 'SWIFT Wire' },
  'GEO': { lang: 'en', currency: 'GEL', currencySymbol: '₾', country: 'Georgia', flag: '🇬🇪', paymentMethod: 'SWIFT Wire' },
  'ARM': { lang: 'en', currency: 'AMD', currencySymbol: '֏', country: 'Armenia', flag: '🇦🇲', paymentMethod: 'SWIFT Wire' },
  'AZE': { lang: 'en', currency: 'AZN', currencySymbol: '₼', country: 'Azerbaijan', flag: '🇦🇿', paymentMethod: 'SWIFT Wire' },
  'SRB': { lang: 'en', currency: 'RSD', currencySymbol: 'дин', country: 'Serbia', flag: '🇷🇸', paymentMethod: 'SWIFT Wire' },
  'MNE': { lang: 'en', currency: 'EUR', currencySymbol: '€', country: 'Montenegro', flag: '🇲🇪', paymentMethod: 'SWIFT Wire' },
  'BIH': { lang: 'en', currency: 'BAM', currencySymbol: 'KM', country: 'Bosnia and Herzegovina', flag: '🇧🇦', paymentMethod: 'SWIFT Wire' },
  'ALB': { lang: 'en', currency: 'ALL', currencySymbol: 'L', country: 'Albania', flag: '🇦🇱', paymentMethod: 'SWIFT Wire' },
  'MKD': { lang: 'en', currency: 'MKD', currencySymbol: 'ден', country: 'North Macedonia', flag: '🇲🇰', paymentMethod: 'SWIFT Wire' },
  'XKX': { lang: 'en', currency: 'EUR', currencySymbol: '€', country: 'Kosovo', flag: '🇽🇰', paymentMethod: 'SWIFT Wire' },

  // Additional Asian Countries
  'MMR': { lang: 'en', currency: 'MMK', currencySymbol: 'Ks', country: 'Myanmar', flag: '🇲🇲', paymentMethod: 'SWIFT Wire' },
  'KHM': { lang: 'en', currency: 'KHR', currencySymbol: '៛', country: 'Cambodia', flag: '🇰🇭', paymentMethod: 'SWIFT Wire' },
  'LAO': { lang: 'en', currency: 'LAK', currencySymbol: '₭', country: 'Laos', flag: '🇱🇦', paymentMethod: 'SWIFT Wire' },
  'MNG': { lang: 'en', currency: 'MNT', currencySymbol: '₮', country: 'Mongolia', flag: '🇲🇳', paymentMethod: 'SWIFT Wire' },
  'BTN': { lang: 'en', currency: 'BTN', currencySymbol: 'Nu.', country: 'Bhutan', flag: '🇧🇹', paymentMethod: 'SWIFT Wire' },
  'MDV': { lang: 'en', currency: 'MVR', currencySymbol: '.ރ', country: 'Maldives', flag: '🇲🇻', paymentMethod: 'SWIFT Wire' }
};

// Language mappings for comprehensive translations
export const languages = {
  pt: 'Português',
  en: 'English', 
  es: 'Español',
  fr: 'Français',
  de: 'Deutsch',
  it: 'Italiano'
};

export default countryMappings;